DROP TABLE IF EXISTS people;
 
CREATE TABLE people  (
    person_id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    first_name VARCHAR(20),
    last_name VARCHAR(20)
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;